name: GitHub Action Automation
on:
  push:
  pull_request:
    branches:
      - master
   
jobs: 
 test:
  name: Running GitHub Action Automation 
  runs-on: macos - latest
  
  steps: 
  - uses: actions/checkout@v1
  - name: Use Node.js ${{ matrix.node-version }}
    uses: action/setup-node@v1
    with: 
      node-version: ${{ matrix.node-version }}
  - name: 
    run: npm
